
spring:
  rabbitmq:
    host: 192.168.229.21
    port: 5672
    username: guest
    password: guest
    virtual-host: /

    #rabbit 消息确认机制，1 确认消息投递到了 exchange，异步 confirms
    publisher-confirms: true
    # 2 确认消息正确路由到了 队列。如果没有正确路由到队列 ，则触发回调
    publisher-returns: true

    #开启消息手动确认
    listener:
      simple:
      # acknowledge-mode ：auto 当队列监听者发生异常时，消息会进入死信队列
        acknowledge-mode: manual
        # 消费者重试机制开启 , mq 处理分布式事务时，放弃这种方案，这个mq的重试机制会阻塞消费者线程，浪费mq性能，使用 定时任务+死信队列代替
#        retry:
#          enabled: true
#          max-attempts: 3 # 最大重试次数，就是消息投递给消费者的重试次数，重试次数不宜过大，否则容易导致消息堆积
#          # 经测试，消息并没有进入死信
#        default-requeue-rejected: false # 达到最大重试次数后，消息是否重如队列，false 表示不重新如队列，成为死信，若配置死信队列，进入死信队列

#    template: 生产者的重试暂时没有测试处理
#      retry:
#        enabled: true # 消息生产者重试开启
#        max-attempts: 3
#        initial-interval: 1000
#        max-interval: 10000
#        multiplier: 1.0
        # publisher-returns: true 配合 ，可以使没有正确路由到队列的消息 返回给消费者

#        mandatory
#        当mandatory标志位设置为true时，如果exchange根据自身类型和消息routeKey无法找到一个符合条件的queue，那么会调用basic.return方法将消息返回给生产者（Basic.Return + Content-Header + Content-Body）；当mandatory设置为false时，出现上述情形broker会直接将消息扔掉。
      mandatory: true

